PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZOV2CAB CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZOV2CAB-ORDEMID .
    FIELD ZOV2CAB-CRIACAO_DATA .
    FIELD ZOV2CAB-CRIACAO_HORA .
    FIELD ZOV2CAB-CRIACAO_USUARIO .
    FIELD ZOV2CAB-CLIENTEID .
    FIELD ZOV2CAB-TOTALITENS .
    FIELD ZOV2CAB-TOTALFRETE .
    FIELD ZOV2CAB-TOTALORDEM .
    FIELD ZOV2CAB-STATUS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZOV2CAB-ORDEMID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
